In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

In [2]:
df = pd.read_csv("test.csv", sep=',')

In [4]:
df

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       1           1043     1          1.8         1  14       0           5   
1       2            841     1          0.5         1   4       1          61   
2       3           1807     1          2.8         0   1       0          27   
3       4           1546     0          0.5         1  18       1          25   
4       5           1434     0          1.4         0  11       1          49   
..    ...            ...   ...          ...       ...  ..     ...         ...   
995   996           1700     1          1.9         0   0       1          54   
996   997            609     0          1.8         1   0       0          13   
997   998           1185     0          1.4         0   1       1           8   
998   999           1533     1          0.5         1   0       0          50   
999  1000           1270     1          0.5         0   4       1          35   

     m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0      0.1        193  ...  16        226      1412  3476    12     7   
1      0.8        191  ...  12        746       857  3895     6     0   
2      0.9        186  ...   4       1270      1366  2396    17    10   
3      0.5         96  ...  20        295      1752  3893    10     0   
4      0.5        108  ...  18        749       810  1773    15     8   
..     ...        ...  ...  ..        ...       ...   ...   ...   ...   
995    0.5        170  ...  17        644       913  2121    14     8   
996    0.9        186  ...   2       1152      1632  1933     8     1   
997    0.5         80  ...  12        477       825  1223     5     0   
998    0.4        171  ...  12         38       832  2509    15    11   
999    0.1        140  ...  19        457       608  2828     9     2   

     talk_time  three_g  touch_screen  wifi  
0            2        0             1     0  
1            7        1             0     0  
2           10        0             1     1  
3            7        1             1     0  
4            7        1             0     1  
..         ...      ...           ...   ...  
995         15        1             1     0  
996         19        0             1     1  
997         14        1             0     0  
998          6        0             1     0  
999          3        1             0     1  

[1000 rows x 21 columns]

In [5]:
x = df.drop(["wifi"], axis = 1)
x.head()

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0   1           1043     1          1.8         1  14       0           5   
1   2            841     1          0.5         1   4       1          61   
2   3           1807     1          2.8         0   1       0          27   
3   4           1546     0          0.5         1  18       1          25   
4   5           1434     0          1.4         0  11       1          49   

   m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0    0.1        193        3  16        226      1412  3476    12     7   
1    0.8        191        5  12        746       857  3895     6     0   
2    0.9        186        3   4       1270      1366  2396    17    10   
3    0.5         96        8  20        295      1752  3893    10     0   
4    0.5        108        6  18        749       810  1773    15     8   

   talk_time  three_g  touch_screen  
0          2        0             1  
1          7        1             0  
2         10        0             1  
3          7        1             1  
4          7        1             0

In [6]:
y = df["wifi"]
y.head()

0    0
1    0
2    1
3    0
4    1
Name: wifi, dtype: int64

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 100)

In [12]:
nb = GaussianNB()

In [13]:
nb_train = nb.fit(x_train, y_train)

In [14]:
y_pred = nb_train.predict(x_test)
y_pred

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1], dtype=int64)

In [15]:
np.array(y_test)

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0], dtype=int64)

In [16]:
nb_train.predict_proba(x_test)

array([[0.36340611, 0.63659389],
       [0.46556949, 0.53443051],
       [0.419941  , 0.580059  ],
       [0.54661737, 0.45338263],
       [0.57059498, 0.42940502],
       [0.54763773, 0.45236227],
       [0.39244648, 0.60755352],
       [0.5065353 , 0.4934647 ],
       [0.58474502, 0.41525498],
       [0.45982023, 0.54017977],
       [0.57923184, 0.42076816],
       [0.45624978, 0.54375022],
       [0.75475668, 0.24524332],
       [0.47301727, 0.52698273],
       [0.55876826, 0.44123174],
       [0.33241826, 0.66758174],
       [0.36474938, 0.63525062],
       [0.53553075, 0.46446925],
       [0.32295235, 0.67704765],
       [0.58153864, 0.41846136],
       [0.61726842, 0.38273158],
       [0.31460504, 0.68539496],
       [0.56645657, 0.43354343],
       [0.31805008, 0.68194992],
       [0.35617048, 0.64382952],
       [0.74063557, 0.25936443],
       [0.39426376, 0.60573624],
       [0.553881  , 0.446119  ],
       [0.49937032, 0.50062968],
       [0.66426708, 0.33573292],
       [0.

In [17]:
confusion_matrix(y_test, y_pred)
f1_score(y_test, y_pred, labels=np.unique(y_pred), average='weighted')

0.529811924769908

In [18]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.53      0.55      0.54       100\n           1       0.53      0.51      0.52       100\n\n    accuracy                           0.53       200\n   macro avg       0.53      0.53      0.53       200\nweighted avg       0.53      0.53      0.53       200\n'